services:
  web:
    container_name: drf_template_web
    build: .
    command: >
      sh -c "python manage.py makemigrations && \
             python manage.py migrate && \
             uvicorn Reporch.asgi:application --host 0.0.0.0 --port 8000 --workers 2 --proxy-headers"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./logs:/app/logs
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - drf_template_network

  celery:
    container_name: drf_template_celery
    build: .
    command: celery -A Reporch worker --loglevel=info --pool=threads -Ofair
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      DJANGO_SETTINGS_MODULE: Reporch.settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - web
    restart: unless-stopped
    networks:
      - drf_template_network

  redis:
    container_name: drf_template_redis
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - drf_template_network

  postgres:
    image: pgvector/pgvector:pg15
    container_name: drf_template_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-drf_template_db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - drf_template_network

networks:
  drf_template_network:
    driver: bridge

volumes:
  postgres_data:
